# Retail Pricing Intelligence Dashboard

## Import Libraries

## Load Dataset

## Data Exploration

## Data Cleaning

## Feature Engineering

## Export Cleaned Dataset

## SQL Analysis

## Conclusion

In [64]:
import pandas as pd
import numpy as np

In [65]:
df = pd.read_csv("../data/raw/fashion_boutique_dataset.csv")

In [66]:
df.head()

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,stock_quantity,customer_rating,is_returned,return_reason
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05,37,3.0,False,NaN
1,FB000002,Tops,Uniqlo,Winter,L,Pink,119.64,0.0,119.64,2025-08-06,2,2.5,False,NaN
2,FB000003,Accessories,Uniqlo,Winter,NaN,Black,33.80,0.0,33.80,2025-08-06,22,4.3,False,NaN
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07,48,2.6,False,NaN
4,FB000005,Tops,Banana Republic,Winter,XL,Black,105.02,0.0,105.02,2025-08-06,10,NaN,False,NaN

In [67]:
df.shape

(2176, 14)

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2176 entries, 0 to 2175
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           2176 non-null   object
 1   category             2176 non-null   object
 2   brand                2176 non-null   object
 3   season               2176 non-null   object
 4   size                 1685 non-null   object
 5   color                2176 non-null   object
 6   original_price       2176 non-null   float64
 7   markdown_percentage  2176 non-null   float64
 8   current_price        2176 non-null   float64
 9   purchase_date        2176 non-null   object
 10  stock_quantity       2176 non-null   int64
 11  customer_rating      1814 non-null   float64
 12  is_returned          2176 non-null   bool
 13  return_reason        320 non-null    object
dtypes: bool(1), float64(4), int64(1), object(8)
memory usage: 223.3+ KB

In [69]:
df.describe()

,original_price,markdown_percentage,current_price,stock_quantity,customer_rating
count,2176.000000,2176.000000,2176.000000,2176.000000,1814.000000
mean,97.200340,12.144715,85.499596,24.937960,2.986604
std,51.637345,18.417786,50.091354,14.451387,1.159722
min,15.140000,0.000000,7.290000,0.000000,1.000000
25%,57.872500,0.000000,46.845000,13.000000,2.000000
50%,88.600000,0.000000,74.885000,25.000000,3.000000
75%,127.630000,22.425000,112.865000,37.000000,4.000000
max,249.980000,59.900000,249.980000,50.000000,5.000000

In [70]:
df.isnull().sum()

product_id                0
category                  0
brand                     0
season                    0
size                    491
color                     0
original_price            0
markdown_percentage       0
current_price             0
purchase_date             0
stock_quantity            0
customer_rating         362
is_returned               0
return_reason          1856
dtype: int64

In [71]:
df.duplicated().sum()

np.int64(0)

In [72]:
df.dtypes

product_id              object
category                object
brand                   object
season                  object
size                    object
color                   object
original_price         float64
markdown_percentage    float64
current_price          float64
purchase_date           object
stock_quantity           int64
customer_rating        float64
is_returned               bool
return_reason           object
dtype: object

In [73]:
df.nunique()

product_id             2176
category                  6
brand                     8
season                    4
size                      6
color                    11
original_price         2061
markdown_percentage     458
current_price          2025
purchase_date           273
stock_quantity           51
customer_rating          41
is_returned               2
return_reason             6
dtype: int64

In [74]:
df["category"].unique()

array(['Outerwear', 'Tops', 'Accessories', 'Shoes', 'Bottoms', 'Dresses'],
      dtype=object)

In [75]:
df["brand"].unique()

array(['Zara', 'Uniqlo', 'Banana Republic', 'Mango', 'H&M', 'Ann Taylor',
       'Gap', 'Forever21'], dtype=object)

In [76]:
df["is_returned"].value_counts()

is_returned
False    1856
True      320
Name: count, dtype: int64

In [77]:
df.isnull().sum()[df.isnull().sum() > 0]

size                491
customer_rating     362
return_reason      1856
dtype: int64

In [78]:
df_clean = df.copy()

In [79]:
df_clean.head()

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,stock_quantity,customer_rating,is_returned,return_reason
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05,37,3.0,False,NaN
1,FB000002,Tops,Uniqlo,Winter,L,Pink,119.64,0.0,119.64,2025-08-06,2,2.5,False,NaN
2,FB000003,Accessories,Uniqlo,Winter,NaN,Black,33.80,0.0,33.80,2025-08-06,22,4.3,False,NaN
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07,48,2.6,False,NaN
4,FB000005,Tops,Banana Republic,Winter,XL,Black,105.02,0.0,105.02,2025-08-06,10,NaN,False,NaN

In [80]:
df_clean = df.copy()

In [81]:
df_clean.head()

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,stock_quantity,customer_rating,is_returned,return_reason
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05,37,3.0,False,NaN
1,FB000002,Tops,Uniqlo,Winter,L,Pink,119.64,0.0,119.64,2025-08-06,2,2.5,False,NaN
2,FB000003,Accessories,Uniqlo,Winter,NaN,Black,33.80,0.0,33.80,2025-08-06,22,4.3,False,NaN
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07,48,2.6,False,NaN
4,FB000005,Tops,Banana Republic,Winter,XL,Black,105.02,0.0,105.02,2025-08-06,10,NaN,False,NaN

In [82]:
df_clean["size"].value_counts(dropna=False)

size
NaN    491
XS     301
S      294
XL     283
XXL    279
L      273
M      255
Name: count, dtype: int64

In [83]:
df_clean["size"] = df_clean["size"].fillna("Unknown")

In [84]:
df_clean["size"].isnull().sum()

np.int64(0)

In [85]:
df_clean["customer_rating"].describe()

count    1814.000000
mean        2.986604
std         1.159722
min         1.000000
25%         2.000000
50%         3.000000
75%         4.000000
max         5.000000
Name: customer_rating, dtype: float64

In [86]:
median_rating = df_clean["customer_rating"].median()
df_clean["customer_rating"] = df_clean["customer_rating"].fillna(median_rating)

In [87]:
df_clean["customer_rating"].isnull().sum()

np.int64(0)

In [88]:
df_clean["purchase_date"] = pd.to_datetime(df_clean["purchase_date"])

In [89]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2176 entries, 0 to 2175
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           2176 non-null   object
 1   category             2176 non-null   object
 2   brand                2176 non-null   object
 3   season               2176 non-null   object
 4   size                 2176 non-null   object
 5   color                2176 non-null   object
 6   original_price       2176 non-null   float64
 7   markdown_percentage  2176 non-null   float64
 8   current_price        2176 non-null   float64
 9   purchase_date        2176 non-null   datetime64[ns]
 10  stock_quantity       2176 non-null   int64
 11  customer_rating      2176 non-null   float64
 12  is_returned          2176 non-null   bool
 13  return_reason        320 non-null    object
dtypes: bool(1), datetime64[ns](1), float64(4), int64(1), object(7)
memory usage: 223.3+ KB

In [90]:
df_clean["discount_amount"] = (
    df_clean["original_price"] - df_clean["current_price"]
)

In [91]:
df_clean.head()

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,stock_quantity,customer_rating,is_returned,return_reason,discount_amount
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05,37,3.0,False,NaN,0.0
1,FB000002,Tops,Uniqlo,Winter,L,Pink,119.64,0.0,119.64,2025-08-06,2,2.5,False,NaN,0.0
2,FB000003,Accessories,Uniqlo,Winter,Unknown,Black,33.80,0.0,33.80,2025-08-06,22,4.3,False,NaN,0.0
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07,48,2.6,False,NaN,0.0
4,FB000005,Tops,Banana Republic,Winter,XL,Black,105.02,0.0,105.02,2025-08-06,10,3.0,False,NaN,0.0

In [92]:
bins = [0, 1000, 3000, float("inf")]
labels = ["Budget", "Mid-Range", "Premium"]
df_clean["price_band"] = pd.cut(
    df_clean["current_price"],
    bins=bins,
    labels=labels
)

In [93]:
df_clean["price_band"].value_counts()

price_band
Budget       2176
Mid-Range       0
Premium         0
Name: count, dtype: int64

In [94]:
df_clean["purchase_month"] = df_clean["purchase_date"].dt.month_name()

In [95]:
df_clean[["purchase_date", "purchase_month"]].head()

  purchase_date purchase_month
0    2025-07-05           July
1    2025-08-06         August
2    2025-08-06         August
3    2025-07-07           July
4    2025-08-06         August

In [96]:
df_clean["return_status"] = df_clean["is_returned"].map({
    True: "Returned",
    False: "Not Returned"
})

In [97]:
df_clean["return_status"].value_counts()

return_status
Not Returned    1856
Returned         320
Name: count, dtype: int64

In [98]:
df_clean.to_csv(
      "../data/cleaned/retail_pricing_cleaned.csv",
    index=False
)

In [99]:
import sqlite3
import pandas as pd

In [100]:
conn = sqlite3.connect("../data/retail_pricing.db")

In [101]:
df_clean.to_sql(
    "retail_pricing",
    conn,
    if_exists="replace",
    index=False
)

2176

In [102]:
query = """
SELECT name
FROM sqlite_master
WHERE type='table';
"""

pd.read_sql(query, conn)

             name
0  retail_pricing

In [103]:
#How many products are there in the database?
query = """
SELECT COUNT(*) AS Total_Products
From retail_pricing;
"""

pd.read_sql(query,conn)

   Total_Products
0            2176

In [104]:
#How many products are there in each category?
query = """
SELECT
    category,
    COUNT(*) AS Total_Products
FROM retail_pricing
GROUP BY category
ORDER BY Total_Products DESC;
"""

pd.read_sql(query, conn)

      category  Total_Products
0  Accessories             402
1      Bottoms             392
2        Shoes             372
3         Tops             359
4    Outerwear             334
5      Dresses             317

In [105]:
#What is the average selling price of each brand?
query = """
SELECT
brand,
ROUND(AVG(current_price),2) AS Avg_Selling_Price
FROM retail_pricing
GROUP BY brand
ORDER BY Avg_Selling_Price DESC;
"""

pd.read_sql(query, conn)

             brand  Avg_Selling_Price
0           Uniqlo              91.66
1  Banana Republic              89.67
2            Mango              88.38
3              H&M              85.81
4             Zara              84.80
5       Ann Taylor              84.38
6        Forever21              80.25
7              Gap              77.81

In [106]:
#Which categories receive the highest average discount?

query = """
SELECT
category,
ROUND(AVG(markdown_percentage),2) AS Avg_Discount
FROM retail_pricing
GROUP BY category
ORDER BY Avg_Discount DESC;
""" 

pd.read_sql(query, conn)

      category  Avg_Discount
0      Bottoms         13.23
1      Dresses         13.17
2        Shoes         12.98
3  Accessories         11.69
4         Tops         10.98
5    Outerwear         10.77

In [107]:
#Which brands have the highest customer ratings?
query = """
SELECT
brand,
ROUND(AVG(customer_rating),2) AS Avg_Rating
FROM retail_pricing
GROUP BY brand
ORDER BY Avg_Rating DESC;
"""

pd.read_sql(query, conn)

             brand  Avg_Rating
0           Uniqlo        3.09
1       Ann Taylor        3.08
2              H&M        3.03
3              Gap        3.03
4  Banana Republic        3.00
5        Forever21        2.97
6             Zara        2.92
7            Mango        2.81

In [108]:
# Which categories have the highest inventory?
query = """
SELECT 
category,
SUM(stock_quantity) AS Total_Stock
FROM retail_pricing
GROUP BY category
ORDER BY Total_Stock DESC;
"""

pd.read_sql(query, conn)

      category  Total_Stock
0  Accessories        10541
1      Bottoms         9442
2        Shoes         9118
3         Tops         8868
4    Outerwear         8368
5      Dresses         7928

In [109]:
#Which season has the highest inventory?
query = """
SELECT 
season,
SUM(stock_quantity) AS Total_Stock
FROM retail_pricing
GROUP BY season
ORDER BY Total_Stock DESC;
"""

pd.read_sql(query, conn)

   season  Total_Stock
0  Summer        14307
1  Spring        13720
2    Fall        13448
3  Winter        12790

In [110]:
#Which brands have the highest inventory?
query = """
SELECT
brand,
SUM(stock_quantity) AS Total_Stock
FROM retail_pricing
GROUP BY brand
ORDER BY Total_Stock DESC;
"""

pd.read_sql(query, conn)

             brand  Total_Stock
0             Zara         7823
1            Mango         7198
2  Banana Republic         6954
3       Ann Taylor         6664
4              H&M         6558
5           Uniqlo         6530
6        Forever21         6428
7              Gap         6110

In [111]:
#How many returned products does each category have?
query = """
SELECT
    season,
    SUM(stock_quantity) AS Total_Stock
FROM retail_pricing
GROUP BY season
ORDER BY Total_Stock DESC;
"""

pd.read_sql(query, conn)

   season  Total_Stock
0  Summer        14307
1  Spring        13720
2    Fall        13448
3  Winter        12790

In [112]:
#What is the return rate for each category?
query = """
SELECT
category,
ROUND(AVG(is_returned) * 100, 2) AS Return_Rate_Percentage
FROM retail_pricing
GROUP BY category
OrDER BY Return_Rate_Percentage DESC;
"""

pd.read_sql(query, conn)

      category  Return_Rate_Percentage
0    Outerwear                   16.17
1      Bottoms                   15.82
2        Shoes                   15.05
3      Dresses                   14.83
4  Accessories                   13.68
5         Tops                   12.81

In [113]:
#Which are the top 10 most expensive products?
query = """
SELECT
product_id,
brand,
category,
current_price
FROM retail_pricing
ORDER BY current_price DESC;
"""

pd.read_sql(query, conn)

     product_id            brand     category  current_price
0      FB002076        Forever21    Outerwear         249.98
1      FB000120             Zara    Outerwear         248.58
2      FB001415           Uniqlo    Outerwear         248.05
3      FB000223              H&M    Outerwear         246.65
4      FB000577              H&M    Outerwear         246.49
...         ...              ...          ...            ...
2171   FB002014           Uniqlo  Accessories          10.48
2172   FB002153           Uniqlo  Accessories           9.71
2173   FB000530           Uniqlo  Accessories           9.58
2174   FB002086        Forever21  Accessories           8.23
2175   FB000050  Banana Republic  Accessories           7.29

[2176 rows x 4 columns]

In [114]:
#Which products have the highest discount?
query = """
SELECT
    product_id,
    brand,
    category,
    markdown_percentage
FROM retail_pricing
ORDER BY markdown_percentage DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  product_id       brand     category  markdown_percentage
0   FB000784         Gap  Accessories                 59.9
1   FB001130        Zara    Outerwear                 59.8
2   FB001376       Mango        Shoes                 59.8
3   FB001950        Zara      Dresses                 59.8
4   FB001672         Gap        Shoes                 59.7
5   FB001725  Ann Taylor        Shoes                 59.7
6   FB000110        Zara      Dresses                 59.5
7   FB001060   Forever21         Tops                 59.5
8   FB001654         Gap      Dresses                 59.5
9   FB000452        Zara         Tops                 59.4

In [115]:
#Which brands have the lowest customer ratings?
query = """
SELECT
brand,
ROUND(AVG(customer_rating), 2) AS Avg_Rating
FROM retail_pricing
GROUP BY brand
ORDER BY Avg_Rating DESC;
"""

pd.read_sql(query, conn)

             brand  Avg_Rating
0           Uniqlo        3.09
1       Ann Taylor        3.08
2              H&M        3.03
3              Gap        3.03
4  Banana Republic        3.00
5        Forever21        2.97
6             Zara        2.92
7            Mango        2.81

In [116]:
#How many products were returned for each reason?
query = """
SELECT
return_reason,
COUNT(*) AS Total_Returns
FROM retail_pricing
WHERE is_returned = 1
GROUP BY return_reason
ORDER BY Total_Returns DESC;
"""

pd.read_sql(query, conn)

    return_reason  Total_Returns
0    Changed Mind             68
1      Size Issue             60
2   Quality Issue             55
3      Wrong Item             47
4  Color Mismatch             46
5         Damaged             44

In [117]:
#Which categories have the highest average selling price?
query = """
SELECT
category,
ROUND(AVG(current_price), 2) AS Avg_Price
FROM retail_pricing
GROUP BY category
ORDER BY Avg_Price DESC;
"""

pd.read_sql(query, conn)

      category  Avg_Price
0    Outerwear     145.73
1        Shoes     110.63
2      Dresses      97.88
3         Tops      66.07
4      Bottoms      61.43
5  Accessories      43.27